name: CI CD Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install blade-formatter
        run: npm install -g blade-formatter

      - name: Check Blade templates format
        run: blade-formatter --diff "resources/views/**/*.blade.php"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run Pint (check only)
        run: ./vendor/bin/pint --test

      - name: Run PHPStan (static analysis)
        run: ./vendor/bin/phpstan analyse --memory-limit=1G app routes database

      - name: Run PHPUnit tests
        run: php artisan test --without-tty

  staging:
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Deploy to staging via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            set -e
            echo "🚀 Deploying Laravel app to staging..."
            cd /var/www/app-absensi-v2
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            echo "✅ Staging deployment completed."
